required = [
  "github.com/golang/protobuf/protoc-gen-go",
]

[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  version = "1.1.0"
  name = "github.com/golang/protobuf"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.13.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-middleware"
  version = "1.0.0"
